language: php

dist: jammy
root: false

env:
  global:
    - setup=stable

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 8.1
      env: setup=lowest
    - php: 8.1.2
      env: setup=lowest

before_install:
  - travis_retry composer self-update
  - travis_retry composer config -g github-oauth.github.com "$GITHUB_TOKEN"

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: composer run test
